name: BIBOL
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.2
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.7.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.2
  provider: ^6.1.5+1
  dio: ^5.9.0
  json_annotation: ^4.9.0
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  flutter_html: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.3.2
  connectivity_plus: ^5.0.0
  web_socket_channel: ^2.4.0
  html_unescape: ^2.0.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

# Config สำหรับ Launcher Icons
flutter_launcher_icons:
  android: true
  ios: true

# Flutter Configuration
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/  
  
  fonts:
    - family: Noto sans laos
      fonts:
        - asset: assets/fonts/NotoSansLao_SemiCondensed-Regular.ttf